### ISSUE TITLE
operatorgroup's target namespaces no longer accepts own namespace

### ISSUE THREAD

**Issue by xelalexv** [nginxinc/nginx-ingress-operator#163]
So far, we have been using version 0.1.0, and in the `OperatorGroup`'s `targetNamespaces`, we set the namespace where the operator is deployed:

```yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  targetNamespaces:
  - nginx-ingress
```

We recently switched to 0.3.0, and with that get an error that own namespace is not supported (did not test 0.2.0). It seems that currently, we can only let the operator group be effective cluster-wide, which we do not want to do. We are running a multi-tenant environment (OpenShift 4.7), and want the operator to only pick up `NginxIngressController` instances from its own namespace. It would be great if the previous behavior could be restored.
